MelodyMatrix/urls.py
#MelodyMatrix/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from .views import return_album
from django.contrib import admin
from django.urls import path, include
from .views import search_view
from user_management.views import profile
from user_management.views import view_profile
from .views import genre_detail, all_genres
from .views import album_inventory
from .views import ArtistListView
from .views import genre_inventory, add_genre, delete_genre
from .views import artist_list
from .views import artist_inventory
from .views import AboutView
from .views import ContactUsView
from .views import LibraryPoliciesView
from .views import SongListView, SongCreateView, SongUpdateView, SongDeleteView
from .views import edit_genre
from .views import add_to_cart, view_cart, checkout, checkout_success



urlpatterns = [
        path('', views.index, name='index'),
        path('album_list/', views.AlbumListView.as_view(), name='album_list'),
        path('album_detail/<int:pk>', views.AlbumDetailView.as_view(), name='album_detail'),
        path('artist_list/', artist_list, name='artist_list'),
        path('artist_detail/<int:pk>', views.ArtistDetailView.as_view(), name='artist_detail'),
        path('my_vinyl/', views.LoanedAlbumsByUserListView.as_view(), name='my_vinyl'),
        path('artist/create/', views.ArtistCreate.as_view(), name='artist_create'),
        path('artist/<int:pk>/update/', views.ArtistUpdate.as_view(), name='artist_update'),
        path('artist/<int:pk>/delete/', views.artist_delete, name='artist_delete'),
        path('album/create/', views.AlbumCreate.as_view(), name='album_create'),
        path('album/<int:pk>/update/', views.AlbumUpdate.as_view(), name='album_update'),
        path('album/<int:pk>/delete/', views.album_delete, name='album_delete'),
        path('album/<uuid:pk>/loan/', views.loan_album_librarian, name='loan_album_librarian'),
        path('manage_inventory/', views.AvailAlbumsListView.as_view(), name='manage_inventory'),
        path('albuminstance/<uuid:pk>/return/', return_album, name='return_album'),
        path('user-management/', include('user_management.urls')),
        path('register/', include('register.urls')),
        path('search/', search_view, name='search'),
        path('profile/', profile, name='profile'),
        path('view_profile/', view_profile, name='view_profile'),
        path('genre_inventory/', genre_inventory, name='genre_inventory'),
        path('genre/<int:pk>/', genre_detail, name='genre_detail'),
        path('add_genre/', add_genre, name='add_genre'),
        path('genre/edit/<int:pk>/', edit_genre, name='edit_genre'),
        path('delete_genre/<int:pk>/', delete_genre, name='delete_genre'),
        path('all_genres/', all_genres, name='all_genres'),
        path('genre_inventory/', genre_inventory, name='genre_inventory'),
        path('manage_albums/', views.album_inventory, name='manage_albums'),
        path('artist_inventory/', artist_inventory, name='artist_inventory'),
        path('about/', AboutView.as_view(), name='about_us'),
        path('library_policies/', LibraryPoliciesView.as_view(), name='library_policies'),
        path('contact_us/', ContactUsView.as_view(), name='contact_us'),
        path('songs/', SongListView.as_view(), name='song_inventory'),
        path('songs/create/', SongCreateView.as_view(), name='song_create'),
        path('songs/<int:pk>/', SongUpdateView.as_view(), name='song_update'),
        path('songs/<int:pk>/delete/', SongDeleteView.as_view(), name='song_delete'),
        path('privacy-policy/', views.privacy_policy_view, name='privacy_policy'),
        path('add_to_cart/<int:album_id>/', add_to_cart, name='add_to_cart'),
        path('view_cart/', view_cart, name='view_cart'),
        path('checkout/', checkout, name='checkout'),
        path('checkout/success/', checkout_success, name='checkout_success'),


]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

locallibrary/urls.py
#locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MelodyMatrix.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}), #serve media files when deployed
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}), #serve static files when deployed
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

register/urls.py
#register/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
]

MelodyMatrix/models.py
#MelodyMatrix/models.py
from django.db import models
from django.urls import reverse  # Used to generate URLs by reversing the URL patterns
import uuid  # Required for unique album instances
from django.contrib.auth.models import User
from datetime import date
from django import forms
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from datetime import timedelta





class Genre(models.Model):
    """Model representing an album genre."""
    name = models.CharField(max_length=200, help_text='Enter an album genre (e.g., Country)')
    image = models.ImageField(upload_to='genre_images/', null=True, blank=True, )

    def __str__(self):
        """String for representing the Model object."""
        return self.name



class Artist(models.Model):
    """Model representing an artist."""
    artist_name = models.CharField(max_length=100)
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this artist')
    summary = models.TextField(max_length=2000, help_text='Enter a brief background of the artist', null=True)
    artist_image = models.ImageField(upload_to='images/', null=True, blank=True)


    class Meta:
        ordering = ['artist_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular artist instance."""
        return reverse('artist_detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.artist_name}'


class Album(models.Model):
    """Model representing an Album."""
    title = models.CharField(max_length=200, null=True)

    # Foreign Key used because album can only have one artist, but artists can have many albums
    artist = models.ForeignKey('Artist', on_delete=models.RESTRICT, null=True)
    summary = models.TextField(max_length=2000, help_text='Enter a brief summary of the album', null=True)

    # ManyToManyField used because genre can contain many albums. Albums can cover many genres.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this album')
    copies_available = models.IntegerField(default=0, help_text='Number of copies available')
    album_image = models.ImageField(upload_to='images/', null=True, blank=True)

    class Meta:
        permissions = (("can_add_album_instance", "Can add album instances"),)

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this album."""
        return reverse('album_detail', args=[str(self.id)])


class Song(models.Model):
    title = models.CharField(max_length=200)
    album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name='songs')

    def __str__(self):
        return self.title


class AlbumInstance(models.Model):
    """Model representing a specific copy of an album (that can be loaned from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular album across whole library')
    album = models.ForeignKey('Album', on_delete=models.RESTRICT, null=True)
    format = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    LOAN_STATUS = (
        ('a', 'Available'), ('o', 'On loan'), ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='a',
    )
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        """Determines if the album is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.album.title})'

    def return_album(self):
        self.LOAN_STATUS = 'a'  # Set status to 'Available'
        self.borrower = None  # Remove the borrower
        self.due_back = None  # Reset due_back date
        self.save()

class LoanCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    albums = models.ManyToManyField('Album')
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField()
    address = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=10)
    state = models.CharField(max_length=100)

    def checkout(self):
        # Check if the cart is not empty
        if self.albums.exists():
            # Create Loan records for each selected album
            for album in self.albums.all():
                Loan.objects.create(borrower=self.user, album=album, due_back=timezone.now() + timedelta(days=14))

            # Clear the cart after successful checkout
            self.albums.clear()
            return True
        else:
            return False

    def __str__(self):
        return f"Cart for {self.user.username}"


class Loan(models.Model):
    borrower = models.ForeignKey(User, on_delete=models.CASCADE)
    album = models.ForeignKey('Album', on_delete=models.CASCADE)
    due_back = models.DateField()

    def __str__(self):
        return f'{self.album.title} - {self.borrower.username}'

MelodyMatrix/forms.py
#MelodyMatrix/forms.py
from .models import AlbumInstance
from django import forms
from .models import Album, Song
from .models import Genre
from .models import LoanCart


class SongForm(forms.ModelForm):
    # Add a field for selecting the album
    album = forms.ModelChoiceField(queryset=Album.objects.all(), required=False)

    class Meta:
        model = Song
        fields = ['title']

    def __init__(self, *args, **kwargs):
        super(SongForm, self).__init__(*args, **kwargs)
        # Optionally, customize the label for the album field
        self.fields['album'].label = 'Album'


class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)


class LoanAlbumForm(forms.ModelForm):
    """Form for a librarian to loan albums."""
    album_title = forms.CharField(disabled=True, required=False)

    # Add a DateField for the due date
    due_back = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        # Display only the album title, borrower, status, and due date to the librarian
        model = AlbumInstance
        fields = ('album_title', 'borrower', 'status', 'due_back',)


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['title', 'artist', 'summary', 'genre', 'copies_available', 'album_image']


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['name', 'image']


class LoanCartForm(forms.ModelForm):
    class Meta:
        model = LoanCart
        fields = ['first_name', 'last_name', 'email', 'address', 'zip_code', 'state']

MelodyMatrix/templates/MelodyMatrix/Privacy_Policy.html
{% extends 'MelodyMatrix/base.html' %}
{% block content %}
    <!-- Purpose: Display Privacy Policy -->
    <div style="margin-bottom: 50px;"></div>
    <header>
        <!-- Heading for Privacy Policy -->
        <h1 class="text-center text-uppercase" style="font-family:'Sitka Text'; font-size: 60px; font-weight: bold ">Privacy Policy</h1>
    </header>
    <div style="margin-bottom: 50px;"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <!-- Subheading and decoration -->
                <h1 class="text-center" style="font-family: 'Magneto', cursive; font-size: 30px; margin-bottom: 10px;">Our Promise</h1>
                <div class="text-center" style="display: flex; justify-content: center;">
                    <p style="border-bottom: 4px solid black; width: 10%; border-radius: 100px;"></p>
                </div>
                <div style="margin-bottom: 15px;"></div>
                <!-- Introduction and commitment -->
                <p style="font-family: 'Palatino', serif; font-size: 18px " class="text-center">
                    At Melody Matrix, we take the preservation of your musical experience seriously, just as we value your privacy and security.
                    Our commitment extends to creating a harmonious world of music where you can explore, enjoy, and share your passion
                    for music without any compromise. Here's how we handle your information in our harmonious world of music.
                </p>
                <div style="margin-bottom: 50px;"></div>
                <!-- Section: Information We Collect -->
                <h2 style="font-family: 'Palatino', serif; font-weight: bold; font-size: 18px; " class="text-center">Information We Collect</h2>
                <p style="font-family: 'Palatino', serif; font-size: 18px ">
                    To ensure the smooth rhythm of your borrowing experience, we collect essential details, including your name, address, and email.
                    These details are used to create your personalized online library card, granting you access to our extensive vinyl collection.
                </p>
                <!-- Section: How We Use Your Information -->
                <h2 style="font-family: 'Palatino', serif; font-weight: bold; font-size: 18px;" class="text-center">How We Use Your Information</h2>
                <p style="font-family: 'Palatino', serif; font-size: 18px ">
                    Your data forms the cornerstone of our service. We use it to facilitate the borrowing process, ensuring timely access
                    to our vinyl collection and personalized experiences tailored to your musical preferences.
                </p>
                <!-- Section: Data Security -->
                <h2 style="font-family: 'Palatino', serif;font-weight: bold; font-size: 18px; " class="text-center ">Data Security</h2>
                <p style="font-family: 'Palatino', serif; font-size: 18px ">
                    Our commitment to safeguarding your information is unwavering. We employ industry-standard security measures
                    to ensure that your data remains as secure as a treasured vinyl record.
                </p>
                <!-- Section: Your Rights, Your Melody -->
                <h2 style="font-family: 'Palatino', serif; font-weight: bold; font-size: 18px;" class="text-center" >Your Rights, Your Melody</h2>
                <p style="font-family: 'Palatino', serif; font-size: 18px ">
                    You hold the conductor's baton when it comes to your data. You have the right to access, modify, or even delete
                    your data. Feel free to contact us to exercise these rights or request more information about your musical journey.
                </p>
                <!-- Section: Policy Updates, Keeping the Beat -->
                <h2 style="font-family: 'Palatino', serif; font-weight: bold; font-size: 18px;" class="text-center" >Policy Updates, Keeping the Beat</h2>
                <p style="font-family: 'Palatino', serif; font-size: 18px ">
                    Just like a great melody evolves, our practices and policies may change. We may update this policy to reflect
                    the changes in our symphony or in response to regulations. So, be sure to check back periodically for any harmonious updates.
                </p>
                <div style="margin-bottom: 50px;"></div>
                <!-- Closing message -->
                <p style="font-family: 'Palatino', serif; font-size: 18px " class="text-center" >
                    Thank you for choosing Melody Matrix, your trust and satisfaction compose the melody that fuels our passion for sharing music!
                </p>
            </div>
        </div>
    </div>
{% endblock %}

MelodyMatrix/templates/MelodyMatrix/about_us.html
{% extends 'MelodyMatrix/base.html' %}

{% block content %}
    <!-- Page Purpose: About The Music Library -->

    {% load static %}
    <!-- Margin for visual separation -->
    <div style="margin-bottom: 50px;"></div>

    <!-- Header Section -->
    <header>
        <h1 class="text-center text-uppercase" style="font-family:'Sitka Text'; font-size: 60px; font-weight: bold ">About The Music Library</h1>
    </header>

    <!-- Main Content Section -->
    <main>
        <!-- Margin for visual separation -->
        <div style="margin-bottom: 50px;"></div>

        <!-- Our Story Section -->
        <section>
            <h3 style="font-family: Magneto; font-size: 35px" class="text-center">Our Story</h3>

            <!-- Underline for decorative purposes -->
            <div class="text-center" style="display: flex; justify-content: center;">
                <p style="border-bottom: 4px solid black; width: 6%; border-radius: 100px;"></p>
            </div>

            <!-- Margin for visual separation -->
            <div style="margin-bottom: 15px;"></div>

            <!-- Paragraphs with story content -->
            <p style="width: 75%; margin: 0 auto; padding: 6px; box-sizing: border-box; font-family: 'Palatino', serif; font-size: 18px">
                In the heart of Omaha, a unique music library, Melody Matrix, was born in the 1990s, thanks to the vision of Mr. Jason Cooper,
                a dedicated music collector with an ardent desire to share the gift of music. Mr. Cooper's personal vinyl record collection served
                as the foundation for this remarkable endeavor, with the sole purpose of lending his cherished records to the people of Omaha, much
                like a library lends books.</p>

            <p style="width: 75%; margin: 0 auto; padding: 6px; box-sizing: border-box; font-family: 'Palatino', serif; font-size: 18px" >
                Initially, the library was a cozy nook that hosted Mr. Cooper's vinyl treasures. As word spread about this unique idea, residents
                started to embrace the idea of sharing their own beloved records with the community. Inspired by the harmony and camaraderie that
                vinyl records brought, they began donating their vinyl to Melody Matrix. It didn't take long for the library's collection to grow,
                and before anyone knew it, it had surpassed 2000 vinyl records, each with its own story and melody.</p>

            <p style="width: 75%; margin: 0 auto; padding: 6px; box-sizing: border-box; font-family: 'Palatino', serif; font-size: 18px">
                Today, that vision lives on through the passionate dedication of Emma Cooper, the torchbearer of her father's dream. She believes
                that music is not only about what you hear but also about the memories, the emotions, and the connection it evokes. With her love
                for music and a desire to bridge the past and the present, she has embarked on an ambitious journey to create this digital platform
                that respects the tradition of Melody Matrix while embracing the convenience of the modern age.</p>
        </section>

        <!-- Image Section -->
        <section>
            <img src="/media/about_banner/Records.jpg" alt="Banner Image" style="width: 100%; height: auto;">
        </section>

        <!-- Margin for visual separation -->
        <div style="margin-bottom: 40px;"></div>

        <!-- Our Mission Section -->
        <section>
            <h3 style="font-family: Magneto; font-size: 35px" class="text-center">Our Mission</h3>

            <!-- Underline for decorative purposes -->
            <div class="text-center" style="display: flex; justify-content: center;">
                <p style="border-bottom: 4px solid black; width: 6%; border-radius: 100px;"></p>
            </div>

            <!-- Paragraphs with mission content -->
            <p style="width: 75%; margin: 0 auto; padding: 6px; box-sizing: border-box; font-family: 'Palatino', serif; font-size: 18px">
                Our website is the embodiment of that vision. It is a testament to our commitment to preserving the spirit of sharing and
                community that Melody Matrix was founded on. As we enter the digital age, we are excited to offer you an opportunity to
                explore our extensive vinyl catalog from the comfort of your own home.</p>

            <p style="width: 75%; margin: 0 auto; padding: 6px; box-sizing: border-box; font-family: 'Palatino', serif; font-size: 18px">
                Discover a treasure trove of over 2000 vinyl records, each with a unique story and melody. From timeless classics to
                hidden gems, our collection represents the tapestry of musical history. Dive into the world of music as you read detailed
                information about each record. Learn about the artist, the album, and the stories behind the melodies that have moved
                generations. Like a traditional library, we still believe in sharing. With just a few clicks, you can request loans,
                ensuring that the spirit of community and the love of music continue to thrive.</p>

            <div style="margin-bottom: 25px;"></div>

            <p class="text-center" style="width: 75%; margin: 0 auto; padding: 6px; box-sizing: border-box; font-family: 'Palatino', serif; font-size: 18px">
                At Melody Matrix, we are not just a digital platform; we are a bridge between the past and the present. We honor the
                legacy of Mr. Jason Cooper and celebrate the dedication of his daughter, Emma, who believes that music is a timeless
                gift meant to be shared. Our website is not just a place to explore vinyl records; it's a place to immerse yourself
                in the stories, emotions, and melodies that define our history.</p>

            <p class="text-center" style="width: 75%; margin: 0 auto; padding: 6px; box-sizing: border-box; font-family: 'Palatino', serif; font-size: 18px">
                Join us on this journey as we keep the melody alive, one click at a time.</p>
        </section>

        <!-- Margin for visual separation -->
        <div style="margin-bottom: 100px;"></div>
    </main>
{% endblock %}

MelodyMatrix/templates/MelodyMatrix/add_genre.html
{% extends "MelodyMatrix/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <!-- Page Purpose: Add Genre -->

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <!-- Heading for Add Genre -->
                        <h2 style="font-family: 'Palatino', serif; font-weight: bold" class="text-center text-uppercase">Add Genre</h2>
                        <div style="margin-bottom: 30px;"></div>

                        <!-- Genre Form -->
                        <form method="post">
                            {% csrf_token %}
                            {{ form|crispy }}

                            <!-- Button Group for Back and Add Genre -->
                            <div class="text-center">
                                <button class="btn btn-dark" onclick="goBack()">Back</button>
                                <button type="submit" class="btn btn-dark">Add Genre</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- JavaScript function to go back -->
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock %}

MelodyMatrix/templates/MelodyMatrix/artist_detail.html
{% extends "MelodyMatrix/base.html" %}
{% block content %}
  <!-- Page Purpose: Display Artist Details and Albums -->

  <div class="container mt-5">
    <div class="row">
      <div class="col-md-12">
        <h1 style="font-family: Magneto; font-size: 60px; font-weight: bold" class="text-center mb-4">{{ artist.artist_name }}</h1>
      </div>
    </div>
    <div style="margin-bottom: 30px;"></div>

    <div class="row">
      <div class="col-md-6 offset-md-3">
        {% if artist.artist_image %}
          <img style="width: 100%; max-height: 600px; max-width: 600px; border-radius: 8px;" src="{{ artist.artist_image.url }}" alt="{{ artist.artist_name }}">
        {% endif %}
      </div>
    </div>
    <div style="margin-bottom: 30px;"></div>

    <div class="row mt-4">
      <div class="col-md-6 offset-md-3">
        <p style="font-family: 'Palatino', serif; font-size: 18px; color: black;">
          <strong>About Artist:</strong> {{ artist.summary }}
        </p>
      </div>
    </div>

    <div style="margin-bottom: 90px;"></div>

    <h2 style="font-family: 'Palatino', serif; font-size: 35px; font-weight: bold" class="text-center mt-4">Albums by {{ artist.artist_name }}</h2>
    <div class="text-center" style="display: flex; justify-content: center;">
      <p style="border-bottom: 4px solid black; width: 8%; border-radius: 100px;"></p>
    </div>

    <div class="card mt-4 mx-auto" style="max-width: 900px;">
      <div class="card-body">
        <div class="row justify-content-center">
          {% for artist_album in artist.album_set.all %}
            <div class="col-md-4 mb-3 mx-auto text-center">
              <a href="{% url 'album_detail' artist_album.id %}" style="text-decoration: none; color: black;">
                <img src="{{ artist_album.album_image.url }}" alt="{{ artist_album.title }}" class="img-fluid">
                <p style="font-family: 'Palatino', serif; font-size: 19px; font-weight: bold" class="mt-2" style="color: black; text-decoration: underline; font-size: 20px;">{{ artist_album.title }}</p>
              </a>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <div style="margin-bottom: 100px;"></div>
{% endblock %}

MelodyMatrix/templates/MelodyMatrix/my_vinyl.html
{% extends "MelodyMatrix/base.html" %}
{% load static %}

{% block content %}
    <!-- Purpose: Display Borrowed Vinyl -->
    {{ loans }}
    <div class="container mt-4">
        <!-- Heading for Borrowed Vinyl section -->
        <h1 class="text-center text-uppercase mb-4" style="font-family:'Sitka Text'; font-weight: bold; font-size: 50px;">My Borrowed Vinyl</h1>
        <div style="margin-bottom: 50px;"></div>
        {% if albuminstance_list %}
            <!-- Displaying Borrowed Vinyls in a row with cards -->
            <div class="row justify-content-center">
                {% for albuminst in albuminstance_list %}
                    <!-- Card for each Borrowed Vinyl -->
                    <div class="col-12 col-md-6 col-lg-4 mb-4">
                        <div class="card h-100 {% if albuminst.is_overdue %}bg-light{% endif %}">
                            <!-- Display Album Cover if available -->
                            {% if albuminst.album.album_image %}
                                <img src="{{ albuminst.album.album_image.url }}" alt="{{ albuminst.album.title }} Cover" class="card-img-top" style="max-height: 200px; object-fit: cover;">
                            {% endif %}
                            <div class="card-body">
                                <!-- Link to Album details page with title -->
                                <h5 class="card-title text-center">
                                    <a href="{% url 'album_detail' albuminst.album.pk %}" style="color: black; text-decoration: none; font-family:'Sitka Text'; font-weight: bold;" class="text-center text-uppercase">{{ albuminst.album.title }}</a>
                                </h5>
                                <!-- Displaying status badge based on Borrowed Vinyl status -->
                                <p class="card-text text-center">
                                    {% if albuminst.status == 'o' %}
                                        <span class="badge bg-success">On Loan</span>
                                    {% elif albuminst.status == 'r' %}
                                        <span class="badge bg-warning">Reserved</span>
                                    {% endif %}
                                </p>
                                <!-- Displaying Due Date for Borrowed Vinyl -->
                                <p class="card-text text-center"><small class="text-muted" style="font-family:'Sitka Text'; font-weight: bold;">Due Date: {{ albuminst.due_back }}</small></p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <!-- Message for no borrowed vinyls -->
            <p class="mt-4 text-center">There are no vinyls borrowed.</p>
        {% endif %}
    </div>
    <div style="margin-bottom: 150px;"></div>
{% endblock %}